apiVersion: v1
kind: Service
metadata:
  name: capstone-project

spec:
  selector:
    app: capstone-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: capstone-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - name: capstone-project
          image: "bamuse/udacity_devops_capston"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"